# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PocketMoneyManager' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SufferTest
  pod 'FoldingCell'
  pod 'ExpandingMenu'
  pod 'lottie-ios'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/AdMob'
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  
end

target 'PocketMoneyManagerTests' do
    
    pod 'Firebase/Auth'
    pod 'Firebase/Core'
    pod 'Firebase/Firestore'

end

post_install do | installer |
    acknowledgements = File.read('Pods/Target Support Files/Pods-SufferTest/Pods-SufferTest-Acknowledgements.markdown', :encoding => Encoding::UTF_8)
    File.write('../SufferTest/SufferTest/Resources/Lisences.txt', acknowledgements)
end
