# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SufferTest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SufferTest
  pod 'FoldingCell'
  pod 'ExpandingMenu'
  pod 'lottie-ios'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/AdMob'
  
end
